[project]
name = "xrag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "accelerate>=1.10.1",
    "datasets>=4.3.0",
    "deepspeed>=0.18.1",
    "flash-attn==2.3.4",
    "ipykernel>=6.31.0",
    "sentencepiece>=0.2.1",
    "transformers>=4.57.1",
    "wandb>=0.22.2",
]
